name: Generate Snake

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
    
  workflow_dispatch:
  
  push:
    branches:
    - main
    
    

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    
    steps:
      # Snake Animation
      - uses: Platane/snk/svg-only@v2
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
